# Generated by Django 3.1.7 on 2021-03-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('xm', 'Xiaomi'), ('sm', 'Samsung'), ('hw', 'Huawei'), ('op', 'Oppo'), ('ap', 'Apple'), ('on', 'Oneplus'), ('rm', 'Realme'), ('po', 'Pocco'), ('ln', 'Lenovo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('a', 'Android Phones'), ('i', 'Iphones'), ('q', 'QWERTY Phones'), ('k', 'Keypad Phones')], max_length=2),
        ),
    ]
