# Generated by Django 3.1.7 on 2021-03-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210321_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung'), ('Huawei', 'Huawei'), ('Oppo', 'Oppo'), ('Apple', 'Apple'), ('Oneplus', 'Oneplus'), ('Realme', 'Realme'), ('Pocco', 'Pocco'), ('Lenovo', 'Lenovo'), ('Nokia', 'Nokia'), ('Jio', 'Jio')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=20),
        ),
    ]
