# Generated by Django 3.1.7 on 2021-03-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210326_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rom',
            field=models.CharField(max_length=20),
        ),
    ]
